# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import numpy
import numpy.typing
# import typing

class ConstantImputer:
    def __init__(self, constant: float) -> None: ...
    @staticmethod
    def zero() -> ConstantImputer:
        ...
    def fit(self, _data:numpy.typing.NDArray[numpy.float64]) -> ConstantImputer:
        ...

    def transform(self, data:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        ...


class KnnImputer:
    k: int
    def __init__(self, k:int=5, metric:str="nan_euclid", weights:str="uniform") -> None: ...
    def fit(self, data:numpy.typing.NDArray[numpy.float64]) -> KnnImputer:
        ...

    def transform(self, data:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        ...


class SimpleImputer:
    def fit(self, data:numpy.typing.NDArray[numpy.float64]) -> SimpleImputer:
        ...

    def transform(self, data:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        ...


class Mice:
    n_iterations: int = 15
    backend: str = "linear"
    alpha: float = 1.0
    def fit(self, data:numpy.typing.NDArray[numpy.float64], *, n_iterations: int = 15, backend: str = "linear", alpha: float = 1.0) -> Mice:
        ...

    def transform(self, data:numpy.typing.NDArray[numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
        ...



