name: default
datasets:
  - 53
  - 222
  - 320
  - 109
  - 19
  - 14
  - 545
  - 2
missing_rates:
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
model_params:
  encoding: label
seeds: 
  - 42
  - 179
  - 88
  - 188
missing_mechanism:
no_cat: False

---
name: mice
model: mice
missing_mechanism: mcar

---
name: knn
model: knn
missing_mechanism: mcar
model_params:
  metric: gower

---
name: missforest
model: missforest
missing_mechanism: mcar
model_params: 
  n_trees: 20
  max_depth: 20
  min_samples_leaf: 3
  encoding: label

---
name: iterative 
model: iterative
missing_mechanism: mcar
model_params: null
no_cat: True

---
name: missforest-py
model: missforest-py
missing_mechanism: mcar
model_params: null
no_cat: True

---
name: knn-sk
model: knn-sk
missing_mechanism: mcar
model_params: null
no_cat: True
